achivement table追加
jphacks/B_2010 pull request #18
Opened 2020-11-04 10:41 UTC by akirato0223

それぞれの値がoptionalかどうかのところが不安ですが、作りました。

2020-11-04 14:31 UTC, Aki-7 requested changes
`wakeupTime` は変更が必要かな

2020-11-04 14:31 UTC, Aki-7 commented on src/entity/Achievement.ts
> +@Entity({ name: 'achivements' })
これテーブル名が複数形にならない?
単数形で揃えたい あとtypo してる.

`name` option なくても クラス名から自動的にtable名作ってくれると思う

2020-11-04 14:31 UTC, Aki-7 commented on src/entity/Achievement.ts
> +  achievementName!: number;
[質問] どういうvalueが入ることを想定してる?

2020-11-04 14:31 UTC, Aki-7 commented on src/entity/User.ts
> +
[nits] 改行残っちゃってそー

2020-11-04 14:31 UTC, Aki-7 commented on src/entity/User.ts
> +  @Column()
nullable にするか、default valueを設定するか、User create 時に値を入れて上げないと行けなさそう.
(Testが落ちてるのもそこだと思う)

2020-11-04 14:31 UTC, Aki-7 commented on src/entity/User.ts
> +  fine?: number;
単位をコメントで明記しておいて欲しい.

2020-11-04 17:10 UTC, Aki-7 commented
スピード重視でマージしないと、先進まない系は勝手にマージしちゃっていいと思う！

2020-11-05 01:00 UTC, akirato0223 commented on src/entity/Achievement.ts
> +  achievementName!: number;
ここ、stringでした

2020-11-05 01:05 UTC, Aki-7 commented on src/entity/Achievement.ts
> +  achievementName!: number;
達成に対してつける名前ってどんなのだろー、って思って。

あと、achievementのカラムだから、ただのnameで良さそうだね。
(なおさんでもいいけど)

2020-11-05 01:09 UTC, Aki-7 approved these changes
lintが落ちてるけど、動きそうだし、LGTM

2020-11-05 01:13 UTC, merged

2020-11-05 01:17 UTC, Aki-7 commented
てか、precommit入れたはずなんだけど、なんでlint落ちてんだ?笑

2020-11-05 01:19 UTC, akirato0223 commented
僕のlintの設定が違う可能性あります？セミコロンとか全部fixすると消えます。

2020-11-05 01:21 UTC, Aki-7 commented
あー、Projectに.eslintrc.jsonがある時はそっちに従う設定にしておいた方が絶対いいと思うよ!

2020-11-05 01:22 UTC, Aki-7 commented
vscodeのeslint extensionとか入れたりするのかな、方法としては

2020-11-05 01:38 UTC, akirato0223 commented
eslintではなくて、prettierからエラー出てました、僕のprettierをオフにすればいいんですかね？

2020-11-05 02:25 UTC, Aki-7 commented
Eslintがprettier を拡張として使っているから、eslintの設定を正しくすればいいはずー

2020-11-05 02:50 UTC, Aki-7 commented
後、lint の fix は `yarn lint --fix` でやったかな?